/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LandlordsRouteImport } from './routes/landlords'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MobilePreviewRouteImport } from './routes/mobile-preview'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppGettingStartedRouteImport } from './routes/app.getting-started'
import { Route as AppLandlordRouteImport } from './routes/app.landlord'
import { Route as AppSelfCheckRouteImport } from './routes/app.self-check'
import { Route as AppTenantRouteImport } from './routes/app.tenant'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as VacanciesIndexRouteImport } from './routes/vacancies.index'
import { Route as VacanciesUnitIdRouteImport } from './routes/vacancies.$unitId'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as AppAdminKycRouteImport } from './routes/app.admin.kyc'
import { Route as AppAdminMapRouteImport } from './routes/app.admin.map'
import { Route as AppAdminMarketRouteImport } from './routes/app.admin.market'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppLandlordIndexRouteImport } from './routes/app.landlord.index'
import { Route as AppLandlordAccountingRouteImport } from './routes/app.landlord.accounting'
import { Route as AppLandlordAuditRouteImport } from './routes/app.landlord.audit'
import { Route as AppLandlordBankingRouteImport } from './routes/app.landlord.banking'
import { Route as AppLandlordExpensesRouteImport } from './routes/app.landlord.expenses'
import { Route as AppLandlordLeasingRouteImport } from './routes/app.landlord.leasing'
import { Route as AppLandlordMaintenanceRouteImport } from './routes/app.landlord.maintenance'
import { Route as AppLandlordMapRouteImport } from './routes/app.landlord.map'
import { Route as AppLandlordMessagesRouteImport } from './routes/app.landlord.messages'
import { Route as AppLandlordNotificationsRouteImport } from './routes/app.landlord.notifications'
import { Route as AppLandlordPayoutsRouteImport } from './routes/app.landlord.payouts'
import { Route as AppLandlordProfileRouteImport } from './routes/app.landlord.profile'
import { Route as AppLandlordReconciliationRouteImport } from './routes/app.landlord.reconciliation'
import { Route as AppLandlordSettingsRouteImport } from './routes/app.landlord.settings'
import { Route as AppLandlordStatementsRouteImport } from './routes/app.landlord.statements'
import { Route as AppLandlordTenantsRouteImport } from './routes/app.landlord.tenants'
import { Route as AppTenantIndexRouteImport } from './routes/app.tenant.index'
import { Route as AppTenantFulizaRouteImport } from './routes/app.tenant.fuliza'
import { Route as AppTenantKycRouteImport } from './routes/app.tenant.kyc'
import { Route as AppTenantLeasesRouteImport } from './routes/app.tenant.leases'
import { Route as AppTenantLeasingRouteImport } from './routes/app.tenant.leasing'
import { Route as AppTenantMaintenanceRouteImport } from './routes/app.tenant.maintenance'
import { Route as AppTenantMessagesRouteImport } from './routes/app.tenant.messages'
import { Route as AppTenantNotificationsRouteImport } from './routes/app.tenant.notifications'
import { Route as AppTenantPaymentsRouteImport } from './routes/app.tenant.payments'
import { Route as ApiPublicHooksViewingRemindersRouteImport } from './routes/api/public/hooks/viewing-reminders'
import { Route as AppLandlordPropertiesIndexRouteImport } from './routes/app.landlord.properties.index'
import { Route as AppLandlordPropertiesPropertyIdRouteImport } from './routes/app.landlord.properties.$propertyId'
import { Route as AppTenantLeasesLeaseIdRouteImport } from './routes/app.tenant.leases.$leaseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordsRoute = LandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilePreviewRoute = MobilePreviewRouteImport.update({
  id: '/mobile-preview',
  path: '/mobile-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppGettingStartedRoute = AppGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => AppRoute,
} as any)
const AppLandlordRoute = AppLandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => AppRoute,
} as any)
const AppSelfCheckRoute = AppSelfCheckRouteImport.update({
  id: '/self-check',
  path: '/self-check',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantRoute = AppTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => AppRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesIndexRoute = VacanciesIndexRouteImport.update({
  id: '/vacancies/',
  path: '/vacancies/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesUnitIdRoute = VacanciesUnitIdRouteImport.update({
  id: '/vacancies/$unitId',
  path: '/vacancies/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminKycRoute = AppAdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMapRoute = AppAdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMarketRoute = AppAdminMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppLandlordIndexRoute = AppLandlordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordAccountingRoute = AppLandlordAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordAuditRoute = AppLandlordAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordBankingRoute = AppLandlordBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordExpensesRoute = AppLandlordExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordLeasingRoute = AppLandlordLeasingRouteImport.update({
  id: '/leasing',
  path: '/leasing',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordMaintenanceRoute = AppLandlordMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordMapRoute = AppLandlordMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordMessagesRoute = AppLandlordMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordNotificationsRoute =
  AppLandlordNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppLandlordRoute,
  } as any)
const AppLandlordPayoutsRoute = AppLandlordPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordProfileRoute = AppLandlordProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordReconciliationRoute =
  AppLandlordReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AppLandlordRoute,
  } as any)
const AppLandlordSettingsRoute = AppLandlordSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordStatementsRoute = AppLandlordStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppLandlordTenantsRoute = AppLandlordTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppLandlordRoute,
} as any)
const AppTenantIndexRoute = AppTenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantFulizaRoute = AppTenantFulizaRouteImport.update({
  id: '/fuliza',
  path: '/fuliza',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantKycRoute = AppTenantKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantLeasesRoute = AppTenantLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantLeasingRoute = AppTenantLeasingRouteImport.update({
  id: '/leasing',
  path: '/leasing',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantMaintenanceRoute = AppTenantMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantMessagesRoute = AppTenantMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantNotificationsRoute = AppTenantNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantPaymentsRoute = AppTenantPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppTenantRoute,
} as any)
const ApiPublicHooksViewingRemindersRoute =
  ApiPublicHooksViewingRemindersRouteImport.update({
    id: '/api/public/hooks/viewing-reminders',
    path: '/api/public/hooks/viewing-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppLandlordPropertiesIndexRoute =
  AppLandlordPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AppLandlordRoute,
  } as any)
const AppLandlordPropertiesPropertyIdRoute =
  AppLandlordPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AppLandlordRoute,
  } as any)
const AppTenantLeasesLeaseIdRoute = AppTenantLeasesLeaseIdRouteImport.update({
  id: '/$leaseId',
  path: '/$leaseId',
  getParentRoute: () => AppTenantLeasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/landlords': typeof LandlordsRoute
  '/login': typeof LoginRoute
  '/mobile-preview': typeof MobilePreviewRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/landlord': typeof AppLandlordRouteWithChildren
  '/app/self-check': typeof AppSelfCheckRoute
  '/app/tenant': typeof AppTenantRouteWithChildren
  '/invite/$code': typeof InviteCodeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/vacancies/$unitId': typeof VacanciesUnitIdRoute
  '/vacancies/': typeof VacanciesIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/kyc': typeof AppAdminKycRoute
  '/app/admin/map': typeof AppAdminMapRoute
  '/app/admin/market': typeof AppAdminMarketRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/landlord/accounting': typeof AppLandlordAccountingRoute
  '/app/landlord/audit': typeof AppLandlordAuditRoute
  '/app/landlord/banking': typeof AppLandlordBankingRoute
  '/app/landlord/expenses': typeof AppLandlordExpensesRoute
  '/app/landlord/leasing': typeof AppLandlordLeasingRoute
  '/app/landlord/maintenance': typeof AppLandlordMaintenanceRoute
  '/app/landlord/map': typeof AppLandlordMapRoute
  '/app/landlord/messages': typeof AppLandlordMessagesRoute
  '/app/landlord/notifications': typeof AppLandlordNotificationsRoute
  '/app/landlord/payouts': typeof AppLandlordPayoutsRoute
  '/app/landlord/profile': typeof AppLandlordProfileRoute
  '/app/landlord/reconciliation': typeof AppLandlordReconciliationRoute
  '/app/landlord/settings': typeof AppLandlordSettingsRoute
  '/app/landlord/statements': typeof AppLandlordStatementsRoute
  '/app/landlord/tenants': typeof AppLandlordTenantsRoute
  '/app/tenant/fuliza': typeof AppTenantFulizaRoute
  '/app/tenant/kyc': typeof AppTenantKycRoute
  '/app/tenant/leases': typeof AppTenantLeasesRouteWithChildren
  '/app/tenant/leasing': typeof AppTenantLeasingRoute
  '/app/tenant/maintenance': typeof AppTenantMaintenanceRoute
  '/app/tenant/messages': typeof AppTenantMessagesRoute
  '/app/tenant/notifications': typeof AppTenantNotificationsRoute
  '/app/tenant/payments': typeof AppTenantPaymentsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/landlord/': typeof AppLandlordIndexRoute
  '/app/tenant/': typeof AppTenantIndexRoute
  '/api/public/hooks/viewing-reminders': typeof ApiPublicHooksViewingRemindersRoute
  '/app/landlord/properties/$propertyId': typeof AppLandlordPropertiesPropertyIdRoute
  '/app/tenant/leases/$leaseId': typeof AppTenantLeasesLeaseIdRoute
  '/app/landlord/properties/': typeof AppLandlordPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/landlords': typeof LandlordsRoute
  '/login': typeof LoginRoute
  '/mobile-preview': typeof MobilePreviewRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/self-check': typeof AppSelfCheckRoute
  '/invite/$code': typeof InviteCodeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/vacancies/$unitId': typeof VacanciesUnitIdRoute
  '/vacancies': typeof VacanciesIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/kyc': typeof AppAdminKycRoute
  '/app/admin/map': typeof AppAdminMapRoute
  '/app/admin/market': typeof AppAdminMarketRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/landlord/accounting': typeof AppLandlordAccountingRoute
  '/app/landlord/audit': typeof AppLandlordAuditRoute
  '/app/landlord/banking': typeof AppLandlordBankingRoute
  '/app/landlord/expenses': typeof AppLandlordExpensesRoute
  '/app/landlord/leasing': typeof AppLandlordLeasingRoute
  '/app/landlord/maintenance': typeof AppLandlordMaintenanceRoute
  '/app/landlord/map': typeof AppLandlordMapRoute
  '/app/landlord/messages': typeof AppLandlordMessagesRoute
  '/app/landlord/notifications': typeof AppLandlordNotificationsRoute
  '/app/landlord/payouts': typeof AppLandlordPayoutsRoute
  '/app/landlord/profile': typeof AppLandlordProfileRoute
  '/app/landlord/reconciliation': typeof AppLandlordReconciliationRoute
  '/app/landlord/settings': typeof AppLandlordSettingsRoute
  '/app/landlord/statements': typeof AppLandlordStatementsRoute
  '/app/landlord/tenants': typeof AppLandlordTenantsRoute
  '/app/tenant/fuliza': typeof AppTenantFulizaRoute
  '/app/tenant/kyc': typeof AppTenantKycRoute
  '/app/tenant/leases': typeof AppTenantLeasesRouteWithChildren
  '/app/tenant/leasing': typeof AppTenantLeasingRoute
  '/app/tenant/maintenance': typeof AppTenantMaintenanceRoute
  '/app/tenant/messages': typeof AppTenantMessagesRoute
  '/app/tenant/notifications': typeof AppTenantNotificationsRoute
  '/app/tenant/payments': typeof AppTenantPaymentsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/landlord': typeof AppLandlordIndexRoute
  '/app/tenant': typeof AppTenantIndexRoute
  '/api/public/hooks/viewing-reminders': typeof ApiPublicHooksViewingRemindersRoute
  '/app/landlord/properties/$propertyId': typeof AppLandlordPropertiesPropertyIdRoute
  '/app/tenant/leases/$leaseId': typeof AppTenantLeasesLeaseIdRoute
  '/app/landlord/properties': typeof AppLandlordPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/landlords': typeof LandlordsRoute
  '/login': typeof LoginRoute
  '/mobile-preview': typeof MobilePreviewRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/landlord': typeof AppLandlordRouteWithChildren
  '/app/self-check': typeof AppSelfCheckRoute
  '/app/tenant': typeof AppTenantRouteWithChildren
  '/invite/$code': typeof InviteCodeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/vacancies/$unitId': typeof VacanciesUnitIdRoute
  '/vacancies/': typeof VacanciesIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/kyc': typeof AppAdminKycRoute
  '/app/admin/map': typeof AppAdminMapRoute
  '/app/admin/market': typeof AppAdminMarketRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/landlord/accounting': typeof AppLandlordAccountingRoute
  '/app/landlord/audit': typeof AppLandlordAuditRoute
  '/app/landlord/banking': typeof AppLandlordBankingRoute
  '/app/landlord/expenses': typeof AppLandlordExpensesRoute
  '/app/landlord/leasing': typeof AppLandlordLeasingRoute
  '/app/landlord/maintenance': typeof AppLandlordMaintenanceRoute
  '/app/landlord/map': typeof AppLandlordMapRoute
  '/app/landlord/messages': typeof AppLandlordMessagesRoute
  '/app/landlord/notifications': typeof AppLandlordNotificationsRoute
  '/app/landlord/payouts': typeof AppLandlordPayoutsRoute
  '/app/landlord/profile': typeof AppLandlordProfileRoute
  '/app/landlord/reconciliation': typeof AppLandlordReconciliationRoute
  '/app/landlord/settings': typeof AppLandlordSettingsRoute
  '/app/landlord/statements': typeof AppLandlordStatementsRoute
  '/app/landlord/tenants': typeof AppLandlordTenantsRoute
  '/app/tenant/fuliza': typeof AppTenantFulizaRoute
  '/app/tenant/kyc': typeof AppTenantKycRoute
  '/app/tenant/leases': typeof AppTenantLeasesRouteWithChildren
  '/app/tenant/leasing': typeof AppTenantLeasingRoute
  '/app/tenant/maintenance': typeof AppTenantMaintenanceRoute
  '/app/tenant/messages': typeof AppTenantMessagesRoute
  '/app/tenant/notifications': typeof AppTenantNotificationsRoute
  '/app/tenant/payments': typeof AppTenantPaymentsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/landlord/': typeof AppLandlordIndexRoute
  '/app/tenant/': typeof AppTenantIndexRoute
  '/api/public/hooks/viewing-reminders': typeof ApiPublicHooksViewingRemindersRoute
  '/app/landlord/properties/$propertyId': typeof AppLandlordPropertiesPropertyIdRoute
  '/app/tenant/leases/$leaseId': typeof AppTenantLeasesLeaseIdRoute
  '/app/landlord/properties/': typeof AppLandlordPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/help'
    | '/landlords'
    | '/login'
    | '/mobile-preview'
    | '/product'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/app/admin'
    | '/app/getting-started'
    | '/app/landlord'
    | '/app/self-check'
    | '/app/tenant'
    | '/invite/$code'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/vacancies/$unitId'
    | '/vacancies/'
    | '/app/admin/audit'
    | '/app/admin/kyc'
    | '/app/admin/map'
    | '/app/admin/market'
    | '/app/admin/settings'
    | '/app/landlord/accounting'
    | '/app/landlord/audit'
    | '/app/landlord/banking'
    | '/app/landlord/expenses'
    | '/app/landlord/leasing'
    | '/app/landlord/maintenance'
    | '/app/landlord/map'
    | '/app/landlord/messages'
    | '/app/landlord/notifications'
    | '/app/landlord/payouts'
    | '/app/landlord/profile'
    | '/app/landlord/reconciliation'
    | '/app/landlord/settings'
    | '/app/landlord/statements'
    | '/app/landlord/tenants'
    | '/app/tenant/fuliza'
    | '/app/tenant/kyc'
    | '/app/tenant/leases'
    | '/app/tenant/leasing'
    | '/app/tenant/maintenance'
    | '/app/tenant/messages'
    | '/app/tenant/notifications'
    | '/app/tenant/payments'
    | '/app/admin/'
    | '/app/landlord/'
    | '/app/tenant/'
    | '/api/public/hooks/viewing-reminders'
    | '/app/landlord/properties/$propertyId'
    | '/app/tenant/leases/$leaseId'
    | '/app/landlord/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/help'
    | '/landlords'
    | '/login'
    | '/mobile-preview'
    | '/product'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/app/getting-started'
    | '/app/self-check'
    | '/invite/$code'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/vacancies/$unitId'
    | '/vacancies'
    | '/app/admin/audit'
    | '/app/admin/kyc'
    | '/app/admin/map'
    | '/app/admin/market'
    | '/app/admin/settings'
    | '/app/landlord/accounting'
    | '/app/landlord/audit'
    | '/app/landlord/banking'
    | '/app/landlord/expenses'
    | '/app/landlord/leasing'
    | '/app/landlord/maintenance'
    | '/app/landlord/map'
    | '/app/landlord/messages'
    | '/app/landlord/notifications'
    | '/app/landlord/payouts'
    | '/app/landlord/profile'
    | '/app/landlord/reconciliation'
    | '/app/landlord/settings'
    | '/app/landlord/statements'
    | '/app/landlord/tenants'
    | '/app/tenant/fuliza'
    | '/app/tenant/kyc'
    | '/app/tenant/leases'
    | '/app/tenant/leasing'
    | '/app/tenant/maintenance'
    | '/app/tenant/messages'
    | '/app/tenant/notifications'
    | '/app/tenant/payments'
    | '/app/admin'
    | '/app/landlord'
    | '/app/tenant'
    | '/api/public/hooks/viewing-reminders'
    | '/app/landlord/properties/$propertyId'
    | '/app/tenant/leases/$leaseId'
    | '/app/landlord/properties'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/help'
    | '/landlords'
    | '/login'
    | '/mobile-preview'
    | '/product'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/app/admin'
    | '/app/getting-started'
    | '/app/landlord'
    | '/app/self-check'
    | '/app/tenant'
    | '/invite/$code'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/vacancies/$unitId'
    | '/vacancies/'
    | '/app/admin/audit'
    | '/app/admin/kyc'
    | '/app/admin/map'
    | '/app/admin/market'
    | '/app/admin/settings'
    | '/app/landlord/accounting'
    | '/app/landlord/audit'
    | '/app/landlord/banking'
    | '/app/landlord/expenses'
    | '/app/landlord/leasing'
    | '/app/landlord/maintenance'
    | '/app/landlord/map'
    | '/app/landlord/messages'
    | '/app/landlord/notifications'
    | '/app/landlord/payouts'
    | '/app/landlord/profile'
    | '/app/landlord/reconciliation'
    | '/app/landlord/settings'
    | '/app/landlord/statements'
    | '/app/landlord/tenants'
    | '/app/tenant/fuliza'
    | '/app/tenant/kyc'
    | '/app/tenant/leases'
    | '/app/tenant/leasing'
    | '/app/tenant/maintenance'
    | '/app/tenant/messages'
    | '/app/tenant/notifications'
    | '/app/tenant/payments'
    | '/app/admin/'
    | '/app/landlord/'
    | '/app/tenant/'
    | '/api/public/hooks/viewing-reminders'
    | '/app/landlord/properties/$propertyId'
    | '/app/tenant/leases/$leaseId'
    | '/app/landlord/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HelpRoute: typeof HelpRoute
  LandlordsRoute: typeof LandlordsRoute
  LoginRoute: typeof LoginRoute
  MobilePreviewRoute: typeof MobilePreviewRoute
  ProductRoute: typeof ProductRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  InviteCodeRoute: typeof InviteCodeRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  VacanciesUnitIdRoute: typeof VacanciesUnitIdRoute
  VacanciesIndexRoute: typeof VacanciesIndexRoute
  ApiPublicHooksViewingRemindersRoute: typeof ApiPublicHooksViewingRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlords': {
      id: '/landlords'
      path: '/landlords'
      fullPath: '/landlords'
      preLoaderRoute: typeof LandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-preview': {
      id: '/mobile-preview'
      path: '/mobile-preview'
      fullPath: '/mobile-preview'
      preLoaderRoute: typeof MobilePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/getting-started': {
      id: '/app/getting-started'
      path: '/getting-started'
      fullPath: '/app/getting-started'
      preLoaderRoute: typeof AppGettingStartedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/landlord': {
      id: '/app/landlord'
      path: '/landlord'
      fullPath: '/app/landlord'
      preLoaderRoute: typeof AppLandlordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/self-check': {
      id: '/app/self-check'
      path: '/self-check'
      fullPath: '/app/self-check'
      preLoaderRoute: typeof AppSelfCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenant': {
      id: '/app/tenant'
      path: '/tenant'
      fullPath: '/app/tenant'
      preLoaderRoute: typeof AppTenantRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies/': {
      id: '/vacancies/'
      path: '/vacancies'
      fullPath: '/vacancies/'
      preLoaderRoute: typeof VacanciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies/$unitId': {
      id: '/vacancies/$unitId'
      path: '/vacancies/$unitId'
      fullPath: '/vacancies/$unitId'
      preLoaderRoute: typeof VacanciesUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/kyc': {
      id: '/app/admin/kyc'
      path: '/kyc'
      fullPath: '/app/admin/kyc'
      preLoaderRoute: typeof AppAdminKycRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/map': {
      id: '/app/admin/map'
      path: '/map'
      fullPath: '/app/admin/map'
      preLoaderRoute: typeof AppAdminMapRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/market': {
      id: '/app/admin/market'
      path: '/market'
      fullPath: '/app/admin/market'
      preLoaderRoute: typeof AppAdminMarketRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/landlord/': {
      id: '/app/landlord/'
      path: '/'
      fullPath: '/app/landlord/'
      preLoaderRoute: typeof AppLandlordIndexRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/accounting': {
      id: '/app/landlord/accounting'
      path: '/accounting'
      fullPath: '/app/landlord/accounting'
      preLoaderRoute: typeof AppLandlordAccountingRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/audit': {
      id: '/app/landlord/audit'
      path: '/audit'
      fullPath: '/app/landlord/audit'
      preLoaderRoute: typeof AppLandlordAuditRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/banking': {
      id: '/app/landlord/banking'
      path: '/banking'
      fullPath: '/app/landlord/banking'
      preLoaderRoute: typeof AppLandlordBankingRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/expenses': {
      id: '/app/landlord/expenses'
      path: '/expenses'
      fullPath: '/app/landlord/expenses'
      preLoaderRoute: typeof AppLandlordExpensesRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/leasing': {
      id: '/app/landlord/leasing'
      path: '/leasing'
      fullPath: '/app/landlord/leasing'
      preLoaderRoute: typeof AppLandlordLeasingRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/maintenance': {
      id: '/app/landlord/maintenance'
      path: '/maintenance'
      fullPath: '/app/landlord/maintenance'
      preLoaderRoute: typeof AppLandlordMaintenanceRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/map': {
      id: '/app/landlord/map'
      path: '/map'
      fullPath: '/app/landlord/map'
      preLoaderRoute: typeof AppLandlordMapRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/messages': {
      id: '/app/landlord/messages'
      path: '/messages'
      fullPath: '/app/landlord/messages'
      preLoaderRoute: typeof AppLandlordMessagesRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/notifications': {
      id: '/app/landlord/notifications'
      path: '/notifications'
      fullPath: '/app/landlord/notifications'
      preLoaderRoute: typeof AppLandlordNotificationsRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/payouts': {
      id: '/app/landlord/payouts'
      path: '/payouts'
      fullPath: '/app/landlord/payouts'
      preLoaderRoute: typeof AppLandlordPayoutsRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/profile': {
      id: '/app/landlord/profile'
      path: '/profile'
      fullPath: '/app/landlord/profile'
      preLoaderRoute: typeof AppLandlordProfileRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/reconciliation': {
      id: '/app/landlord/reconciliation'
      path: '/reconciliation'
      fullPath: '/app/landlord/reconciliation'
      preLoaderRoute: typeof AppLandlordReconciliationRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/settings': {
      id: '/app/landlord/settings'
      path: '/settings'
      fullPath: '/app/landlord/settings'
      preLoaderRoute: typeof AppLandlordSettingsRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/statements': {
      id: '/app/landlord/statements'
      path: '/statements'
      fullPath: '/app/landlord/statements'
      preLoaderRoute: typeof AppLandlordStatementsRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/tenants': {
      id: '/app/landlord/tenants'
      path: '/tenants'
      fullPath: '/app/landlord/tenants'
      preLoaderRoute: typeof AppLandlordTenantsRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/tenant/': {
      id: '/app/tenant/'
      path: '/'
      fullPath: '/app/tenant/'
      preLoaderRoute: typeof AppTenantIndexRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/tenant/fuliza': {
      id: '/app/tenant/fuliza'
      path: '/fuliza'
      fullPath: '/app/tenant/fuliza'
      preLoaderRoute: typeof AppTenantFulizaRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/tenant/kyc': {
      id: '/app/tenant/kyc'
      path: '/kyc'
      fullPath: '/app/tenant/kyc'
      preLoaderRoute: typeof AppTenantKycRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/tenant/leases': {
      id: '/app/tenant/leases'
      path: '/leases'
      fullPath: '/app/tenant/leases'
      preLoaderRoute: typeof AppTenantLeasesRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/tenant/leasing': {
      id: '/app/tenant/leasing'
      path: '/leasing'
      fullPath: '/app/tenant/leasing'
      preLoaderRoute: typeof AppTenantLeasingRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/tenant/maintenance': {
      id: '/app/tenant/maintenance'
      path: '/maintenance'
      fullPath: '/app/tenant/maintenance'
      preLoaderRoute: typeof AppTenantMaintenanceRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/tenant/messages': {
      id: '/app/tenant/messages'
      path: '/messages'
      fullPath: '/app/tenant/messages'
      preLoaderRoute: typeof AppTenantMessagesRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/tenant/notifications': {
      id: '/app/tenant/notifications'
      path: '/notifications'
      fullPath: '/app/tenant/notifications'
      preLoaderRoute: typeof AppTenantNotificationsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/tenant/payments': {
      id: '/app/tenant/payments'
      path: '/payments'
      fullPath: '/app/tenant/payments'
      preLoaderRoute: typeof AppTenantPaymentsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/api/public/hooks/viewing-reminders': {
      id: '/api/public/hooks/viewing-reminders'
      path: '/api/public/hooks/viewing-reminders'
      fullPath: '/api/public/hooks/viewing-reminders'
      preLoaderRoute: typeof ApiPublicHooksViewingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/landlord/properties/': {
      id: '/app/landlord/properties/'
      path: '/properties'
      fullPath: '/app/landlord/properties/'
      preLoaderRoute: typeof AppLandlordPropertiesIndexRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/landlord/properties/$propertyId': {
      id: '/app/landlord/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/app/landlord/properties/$propertyId'
      preLoaderRoute: typeof AppLandlordPropertiesPropertyIdRouteImport
      parentRoute: typeof AppLandlordRoute
    }
    '/app/tenant/leases/$leaseId': {
      id: '/app/tenant/leases/$leaseId'
      path: '/$leaseId'
      fullPath: '/app/tenant/leases/$leaseId'
      preLoaderRoute: typeof AppTenantLeasesLeaseIdRouteImport
      parentRoute: typeof AppTenantLeasesRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminKycRoute: typeof AppAdminKycRoute
  AppAdminMapRoute: typeof AppAdminMapRoute
  AppAdminMarketRoute: typeof AppAdminMarketRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminKycRoute: AppAdminKycRoute,
  AppAdminMapRoute: AppAdminMapRoute,
  AppAdminMarketRoute: AppAdminMarketRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppLandlordRouteChildren {
  AppLandlordAccountingRoute: typeof AppLandlordAccountingRoute
  AppLandlordAuditRoute: typeof AppLandlordAuditRoute
  AppLandlordBankingRoute: typeof AppLandlordBankingRoute
  AppLandlordExpensesRoute: typeof AppLandlordExpensesRoute
  AppLandlordLeasingRoute: typeof AppLandlordLeasingRoute
  AppLandlordMaintenanceRoute: typeof AppLandlordMaintenanceRoute
  AppLandlordMapRoute: typeof AppLandlordMapRoute
  AppLandlordMessagesRoute: typeof AppLandlordMessagesRoute
  AppLandlordNotificationsRoute: typeof AppLandlordNotificationsRoute
  AppLandlordPayoutsRoute: typeof AppLandlordPayoutsRoute
  AppLandlordProfileRoute: typeof AppLandlordProfileRoute
  AppLandlordReconciliationRoute: typeof AppLandlordReconciliationRoute
  AppLandlordSettingsRoute: typeof AppLandlordSettingsRoute
  AppLandlordStatementsRoute: typeof AppLandlordStatementsRoute
  AppLandlordTenantsRoute: typeof AppLandlordTenantsRoute
  AppLandlordIndexRoute: typeof AppLandlordIndexRoute
  AppLandlordPropertiesPropertyIdRoute: typeof AppLandlordPropertiesPropertyIdRoute
  AppLandlordPropertiesIndexRoute: typeof AppLandlordPropertiesIndexRoute
}

const AppLandlordRouteChildren: AppLandlordRouteChildren = {
  AppLandlordAccountingRoute: AppLandlordAccountingRoute,
  AppLandlordAuditRoute: AppLandlordAuditRoute,
  AppLandlordBankingRoute: AppLandlordBankingRoute,
  AppLandlordExpensesRoute: AppLandlordExpensesRoute,
  AppLandlordLeasingRoute: AppLandlordLeasingRoute,
  AppLandlordMaintenanceRoute: AppLandlordMaintenanceRoute,
  AppLandlordMapRoute: AppLandlordMapRoute,
  AppLandlordMessagesRoute: AppLandlordMessagesRoute,
  AppLandlordNotificationsRoute: AppLandlordNotificationsRoute,
  AppLandlordPayoutsRoute: AppLandlordPayoutsRoute,
  AppLandlordProfileRoute: AppLandlordProfileRoute,
  AppLandlordReconciliationRoute: AppLandlordReconciliationRoute,
  AppLandlordSettingsRoute: AppLandlordSettingsRoute,
  AppLandlordStatementsRoute: AppLandlordStatementsRoute,
  AppLandlordTenantsRoute: AppLandlordTenantsRoute,
  AppLandlordIndexRoute: AppLandlordIndexRoute,
  AppLandlordPropertiesPropertyIdRoute: AppLandlordPropertiesPropertyIdRoute,
  AppLandlordPropertiesIndexRoute: AppLandlordPropertiesIndexRoute,
}

const AppLandlordRouteWithChildren = AppLandlordRoute._addFileChildren(
  AppLandlordRouteChildren,
)

interface AppTenantLeasesRouteChildren {
  AppTenantLeasesLeaseIdRoute: typeof AppTenantLeasesLeaseIdRoute
}

const AppTenantLeasesRouteChildren: AppTenantLeasesRouteChildren = {
  AppTenantLeasesLeaseIdRoute: AppTenantLeasesLeaseIdRoute,
}

const AppTenantLeasesRouteWithChildren = AppTenantLeasesRoute._addFileChildren(
  AppTenantLeasesRouteChildren,
)

interface AppTenantRouteChildren {
  AppTenantFulizaRoute: typeof AppTenantFulizaRoute
  AppTenantKycRoute: typeof AppTenantKycRoute
  AppTenantLeasesRoute: typeof AppTenantLeasesRouteWithChildren
  AppTenantLeasingRoute: typeof AppTenantLeasingRoute
  AppTenantMaintenanceRoute: typeof AppTenantMaintenanceRoute
  AppTenantMessagesRoute: typeof AppTenantMessagesRoute
  AppTenantNotificationsRoute: typeof AppTenantNotificationsRoute
  AppTenantPaymentsRoute: typeof AppTenantPaymentsRoute
  AppTenantIndexRoute: typeof AppTenantIndexRoute
}

const AppTenantRouteChildren: AppTenantRouteChildren = {
  AppTenantFulizaRoute: AppTenantFulizaRoute,
  AppTenantKycRoute: AppTenantKycRoute,
  AppTenantLeasesRoute: AppTenantLeasesRouteWithChildren,
  AppTenantLeasingRoute: AppTenantLeasingRoute,
  AppTenantMaintenanceRoute: AppTenantMaintenanceRoute,
  AppTenantMessagesRoute: AppTenantMessagesRoute,
  AppTenantNotificationsRoute: AppTenantNotificationsRoute,
  AppTenantPaymentsRoute: AppTenantPaymentsRoute,
  AppTenantIndexRoute: AppTenantIndexRoute,
}

const AppTenantRouteWithChildren = AppTenantRoute._addFileChildren(
  AppTenantRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppGettingStartedRoute: typeof AppGettingStartedRoute
  AppLandlordRoute: typeof AppLandlordRouteWithChildren
  AppSelfCheckRoute: typeof AppSelfCheckRoute
  AppTenantRoute: typeof AppTenantRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppGettingStartedRoute: AppGettingStartedRoute,
  AppLandlordRoute: AppLandlordRouteWithChildren,
  AppSelfCheckRoute: AppSelfCheckRoute,
  AppTenantRoute: AppTenantRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HelpRoute: HelpRoute,
  LandlordsRoute: LandlordsRoute,
  LoginRoute: LoginRoute,
  MobilePreviewRoute: MobilePreviewRoute,
  ProductRoute: ProductRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  InviteCodeRoute: InviteCodeRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  VacanciesUnitIdRoute: VacanciesUnitIdRoute,
  VacanciesIndexRoute: VacanciesIndexRoute,
  ApiPublicHooksViewingRemindersRoute: ApiPublicHooksViewingRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
